<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NIS-PC091" name="TestCialfoNew.ProfileEditTest" tests="7" failures="1" timestamp="25 Apr 2017 12:24:00 GMT" time="10.567" errors="0">
  <testcase name="verifyProfileNameinOverviewpage" time="1.422" classname="TestCialfoNew.ProfileEditTest">
    <failure type="java.lang.AssertionError" message="expected [Samsung SwimClub] but found []">
      <![CDATA[java.lang.AssertionError: expected [Samsung SwimClub] but found []
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at TestCialfoNew.ProfileEditTest.verifyProfileNameinOverviewpage(ProfileEditTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </failure>
  </testcase> <!-- verifyProfileNameinOverviewpage -->
  <testcase name="enterAddressAndSave" time="1.470" classname="TestCialfoNew.ProfileEditTest"/>
  <testcase name="checkStreetUpdatedOrNot" time="0.934" classname="TestCialfoNew.ProfileEditTest"/>
  <testcase name="verifyPersonalInfoIsUpdatedOrNot" time="0.327" classname="TestCialfoNew.ProfileEditTest"/>
  <testcase name="profileNameInTopRightSide" time="1.247" classname="TestCialfoNew.ProfileEditTest"/>
  <testcase name="enterValuesInPersonalInfoAndCheckSucessMessage" time="5.022" classname="TestCialfoNew.ProfileEditTest"/>
  <testcase name="profileNameInSecondaryMenu" time="0.145" classname="TestCialfoNew.ProfileEditTest"/>
</testsuite> <!-- TestCialfoNew.ProfileEditTest -->
